// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package store

import (
	"context"
)

const getPlatformAPIKeyByHash = `-- name: GetPlatformAPIKeyByHash :one
select id, tenant_id, name, key_hash, status
from platform_api_keys
where key_hash = $1
`

type GetPlatformAPIKeyByHashRow struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
	KeyHash  string `json:"key_hash"`
	Status   string `json:"status"`
}

func (q *Queries) GetPlatformAPIKeyByHash(ctx context.Context, keyHash string) (GetPlatformAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getPlatformAPIKeyByHash, keyHash)
	var i GetPlatformAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyHash,
		&i.Status,
	)
	return i, err
}
