// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ByokCredential struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	Provider        string             `json:"provider"`
	EncryptedSecret string             `json:"encrypted_secret"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PlatformApiKey struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProviderCredential struct {
	ID              string             `json:"id"`
	Provider        string             `json:"provider"`
	DisplayName     string             `json:"display_name"`
	SupportedModels []string           `json:"supported_models"`
	EncryptedSecret string             `json:"encrypted_secret"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
