// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_credentials.sql

package store

import (
	"context"
)

const listActiveProviderCredentials = `-- name: ListActiveProviderCredentials :many
select id, provider, display_name, supported_models, base_url, encrypted_secret, secret_ref, credential_mode, status
from provider_credentials
where status = 'active'
order by created_at asc, id asc
`

type ListActiveProviderCredentialsRow struct {
	ID              string   `json:"id"`
	Provider        string   `json:"provider"`
	DisplayName     string   `json:"display_name"`
	SupportedModels []string `json:"supported_models"`
	BaseUrl         string   `json:"base_url"`
	EncryptedSecret string   `json:"encrypted_secret"`
	SecretRef       string   `json:"secret_ref"`
	CredentialMode  string   `json:"credential_mode"`
	Status          string   `json:"status"`
}

func (q *Queries) ListActiveProviderCredentials(ctx context.Context) ([]ListActiveProviderCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listActiveProviderCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProviderCredentialsRow
	for rows.Next() {
		var i ListActiveProviderCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.DisplayName,
			&i.SupportedModels,
			&i.BaseUrl,
			&i.EncryptedSecret,
			&i.SecretRef,
			&i.CredentialMode,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
