// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_credentials.sql

package store

import (
	"context"
)

const listActiveProviderCredentials = `-- name: ListActiveProviderCredentials :many
select id, provider, display_name, encrypted_secret, status
from provider_credentials
where status = 'active'
`

type ListActiveProviderCredentialsRow struct {
	ID              string `json:"id"`
	Provider        string `json:"provider"`
	DisplayName     string `json:"display_name"`
	EncryptedSecret string `json:"encrypted_secret"`
	Status          string `json:"status"`
}

func (q *Queries) ListActiveProviderCredentials(ctx context.Context) ([]ListActiveProviderCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listActiveProviderCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProviderCredentialsRow
	for rows.Next() {
		var i ListActiveProviderCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.DisplayName,
			&i.EncryptedSecret,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
