// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	GetPlatformAPIKeyByHash(ctx context.Context, keyHash string) (GetPlatformAPIKeyByHashRow, error)
	GetTenantByID(ctx context.Context, id string) (GetTenantByIDRow, error)
	ListActiveProviderCredentials(ctx context.Context) ([]ListActiveProviderCredentialsRow, error)
	ListActiveTenants(ctx context.Context) ([]ListActiveTenantsRow, error)
}

var _ Querier = (*Queries)(nil)
