// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package store

import (
	"context"
)

const getTenantByID = `-- name: GetTenantByID :one
select
  t.id,
  t.name,
  t.status,
  coalesce(q.allowed_models, '{}')::text[] as allowed_models
from tenants t
left join tenant_quota_policies q on q.tenant_id = t.id
where t.id = $1
`

type GetTenantByIDRow struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Status        string   `json:"status"`
	AllowedModels []string `json:"allowed_models"`
}

func (q *Queries) GetTenantByID(ctx context.Context, id string) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i GetTenantByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Status, &i.AllowedModels)
	return i, err
}

const listActiveTenants = `-- name: ListActiveTenants :many
select id, name, status
from tenants
where status = 'active'
`

type ListActiveTenantsRow struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) ListActiveTenants(ctx context.Context) ([]ListActiveTenantsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTenantsRow
	for rows.Next() {
		var i ListActiveTenantsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
